version: "3"
services:
  chain:
    image: "iexechub/poco-chaintest:5.3.0-token-parity"
    restart: unless-stopped
    expose:
      - 8545
      - 8546
    ports:
      - 8545:8545
      - 8546:8546

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - ${DATA}/ipfs:/data/ipfs

  postgres:
    image: postgres
    restart: unless-stopped
    command:
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
     - ${DATA}/postgres:/var/lib/postgresql/data

  graphnode:
    image: graphprotocol/graph-node
    restart: unless-stopped
    depends_on:
      - ipfs
      - postgres
      - chain
    ports:
      - 8000:8000 # http
      - 8001:8001 # ws
      - 8020:8020 # deploy
      - 8030:8030 # monitoring
      - 8040:8040 # prometeus
    environment:
      RUST_BACKTRACE: 1
      RUST_BACKTRACE: full
      postgres_host: postgres
      postgres_user: "${DB_USER}"
      postgres_pass: "${DB_PASSWORD}"
      postgres_db: "${DB_NAME}"
      ipfs: "ipfs:5001"
      ethereum: "test:http://chain:8545"
      GRAPH_NODE_ID: "graphnode_id"
