version: "3"

networks:
  thegraph-bellecour:
  bellecour:
    external:
      name: bellecour_blockchain
  thegraph-viviani:
  viviani:
    external:
      name: viviani_blockchain
  
services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    restart: unless-stopped
    networks:
      - thegraph-bellecour
      - thegraph-viviani
    expose:
      - 5001
    ports:
      - 5001:5001
    volumes:
      - ${DATA}/ipfs:/data/ipfs

  postgres-viviani:
    image: postgres
    restart: unless-stopped
    networks:
      - thegraph-viviani
    command:
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
    expose:
      - 5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
     - ${DATA}/viviani/postgres:/var/lib/postgresql/data

  graphnode-viviani:
    image: graphprotocol/graph-node
    restart: unless-stopped
    networks:
      - viviani
      - thegraph-viviani
    depends_on:
      - ipfs
      - postgres-viviani
    ports:
      - 13300:8000 # http
      - 13301:8001 # ws
      - 13320:8020 # deploy
      - 13330:8030 # monitoring
      - 13340:8040 # prometeus
    environment:
      RUST_BACKTRACE: 1
      RUST_BACKTRACE: full
      postgres_host: postgres-viviani
      postgres_user: "${DB_USER}"
      postgres_pass: "${DB_PASSWORD}"
      postgres_db: "${DB_NAME}"
      ipfs: "ipfs:5001"
      ethereum: "viviani:http://viviani-archive-node:8545"
      GRAPH_NODE_ID: "graphnode_id"

  postgres-bellecour:
    image: postgres
    restart: unless-stopped
    networks:
      - thegraph-bellecour
    command:
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
    expose:
      - 5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
     - ${DATA}/bellecour/postgres:/var/lib/postgresql/data

  graphnode-bellecour:
    image: graphprotocol/graph-node
    restart: unless-stopped
    networks:
      - bellecour
      - thegraph-bellecour
    depends_on:
      - ipfs
      - postgres-bellecour
    ports:
      - 13400:8000 # http
      - 13401:8001 # ws
      - 13420:8020 # deploy
      - 13430:8030 # monitoring
      - 13440:8040 # prometeus
    environment:
      RUST_BACKTRACE: 1
      RUST_BACKTRACE: full
      postgres_host: postgres-bellecour
      postgres_user: "${DB_USER}"
      postgres_pass: "${DB_PASSWORD}"
      postgres_db: "${DB_NAME}"
      ipfs: "ipfs:5001"
      ethereum: "bellecour:http://bellecour-archive-node:8545"
      GRAPH_NODE_ID: "graphnode_id"
