version: "3"

networks:
  thegraph:
  blockchain:
    external:
      name: viviani_blockchain

services:
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    restart: unless-stopped
    networks:
      - thegraph
    expose:
      - 5001
    ports:
      - 5001:5001
    volumes:
      - ${DATA}/ipfs:/data/ipfs

  postgres:
    image: postgres:12
    restart: unless-stopped
    networks:
      - thegraph
    command:
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
    expose:
      - 5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ${DATA}/postgres:/var/lib/postgresql/data

  graphnode:
    image: graphprotocol/graph-node:v0.27.0
    restart: unless-stopped
    networks:
      - blockchain
      - thegraph
    depends_on:
      - ipfs
      - postgres
    ports:
      - 8000:8000 # http
      - 8001:8001 # ws
      - 8020:8020 # deploy
      - 8030:8030 # monitoring
      - 8040:8040 # prometeus
    environment:
      RUST_BACKTRACE: 1
      postgres_host: postgres
      postgres_user: "${DB_USER}"
      postgres_pass: "${DB_PASSWORD}"
      postgres_db: "${DB_NAME}"
      ipfs: "ipfs:5001"
      ethereum: "bellecour:http://bellecour-archive-node:8545"
      GRAPH_NODE_ID: "graphnode_id"
