on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - develop
      - release/*
      - hotfix/*
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init
        run: npm ci
      - name: Run Coverage
        run: (npm run coverage 2>&1) | tee /tmp/coverage.out | cat
      - name: Check coverage
        run: cat /tmp/coverage.out | grep "Global test coverage"
